server:
  port: 8001

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 8.142.91.227
      port: 6379
      password: 123456
  mvc:
    view:
      prefix: /templates/
      suffix: .html
short-link:
  stats:
    locale:
      amap-key: 08f06fc37d39803028f29c42ca6898b4